maxHearts: 20
buffs:
- /effect <plr> 5 9999 5 true
- /effect <plr> 10 9999 1 true
- /effect <plr> 21 9999 4 true
- /give <plr> 420 1 16:5 name:&6Am&7az&eon&8ia&6n_&eLasso
- /give <plr> minecraft:iron_sword 1 16:5 name:&6Am&7az&eon&8ia&6n_&eSword
- /give <plr> minecraft:bow 1 50:1 51:1 name:&6Am&7az&eon&8ia&6n_&eBow
- /give <plr> minecraft:arrow 10
- /give <plr> minecraft:shield 1 0 name:&6Am&7az&eon&8ia&6n_&eShield
- /give <plr> minecraft:iron_helmet 1 0 0:10 1:10 3:10 4:10 7:10 name:&6Am&7az&eon&8ia&6n_&eHe&6lm&7et
- /give <plr> minecraft:iron_chestplate 1 0 0:10 1:10 3:10 4:10 7:10 name:&6Am&7az&eon&8ia&6n_&eCh&6es&7tpl&8ate
- /give <plr> minecraft:iron_leggings 1 0 0:10 1:10 3:10 4:10 7:10 name:&6Am&7az&eon&8ia&6n_&eLe&7gg&6in&8gs
- /give <plr> minecraft:iron_boots 1 0 0:10 1:10 3:10 4:10 7:10 name:&6Am&7az&eon&8ia&6n_&eBo&6o&7ts
chatcolor: '&6'
class: amazonwarrior
haste: 6
jump: 6
name: §6§lAm§7§laz§e§lon §8§lWa§6§lrr§elior
op: false
permissions:
  superherocity:
  - ch.alias.amazonwarrior
  - ch.alias.carryplayer
  - ch.alias.dismountplayer
powers:
- /buff
- /jump <0-3>
- /run <0-3>
- /haste <0-3>
- /carryplayer <player>
- /dismountplayer
run: 3
sig: eepmrmhijzizs8yvzov5onl5bzfknaothta96lngfsukwt61tvatbdmkhjn8irjtlox/rrrGaYGpQ9yET826n7LG3J+aI++lK3F5tNst7B3XzKd4DsJA6grOF1LDBTKRIq5gL3u/UB5/pU+K6ROakXmDq1MO2d2hUUIiNzuc0ePwmCuEt7r066eKbD09TlxcIdqwa/rg8ip5C2KQ24Ym4SYdYzWfqwbGTUHfPns+ls6acVkLoGHWar/mj30oBkOIQDBsLm/ScSkPlg+wFP1RnuuLcXW4EMs8Kxl1thDVUWgP2nW/08P6X88lZ7P8erJZCiaG2TJu/q8YVMbwd8Gpa94SrWV4PXvDN3ZXl1WXLG/PIGDoTUGM5ppzfLpABx6MD+8HyUih6gsngNGD7t2OStRjLi3yBQv3hTOZfZ0V5rEYEUAhQHyBeTzpltQ1a3zLsuK3QF0XwpBuHjENoHaSdKz9szkeLgwNWpzS5uhMmpXdHN9NejX28jFTVNHxu3UGcPMDR2641qlCY46cNxhyvCIE5lElsxG9mN1D1GpFHrNU8NUUYc1TA7KyJuW+qWGRC6Ig4j9ILg0GsPNimcKFE8YSrr7KaA/dIfXB9RmAHwrK5sgp86Bahbh/PG3xcI9k1U3AgtSDqYAfhoCIdbUrRcsUFkSahkOU94ulrFVIDMs=
speech: For the gods! And for Queen Hyppolita!
trail: ''
val: eyj0aw1lc3rhbxaioje1mja0njm4otazndksinbyb2zpbgvjzci6imm4yjg4mtmxntjkndrhzja5ntkzzgrjzgizzdu2mdu4iiwichjvzmlszu5hbwuioij4qjfzacisinnpz25hdhvyzvjlcxvpcmvkijp0cnvllcj0zxh0dxjlcyi6eyjts0loijp7invybci6imh0dha6ly90zxh0dxjlcy5taw5ly3jhznqubmv0l3rlehr1cmuvode2zgyxowywztkxoty5odjjyjnjzjcxyjbhytliyjm1mwmzogiyntexmzaznzlknwjjndy0owvhnddlnzcilcjtzxrhzgf0ysi6eyjtb2rlbci6innsaw0ifx19fq%3D%3D/
